import os
import shutil
import re

# 1. Create directories
dirs = ['src/caelum/static', 'config', 'deploy', 'scripts/hotfixes', 'docs']
for d in dirs:
    os.makedirs(d, exist_ok=True)

# 2. Move files
moves = {
    'caelum_server.py': 'src/caelum/server.py',
    'caelum_ai_analyzer.py': 'src/caelum/ai_analyzer.py',
    'caelum_session_manager.py': 'src/caelum/session_manager.py',
    'caelum_tools_framework.py': 'src/caelum/tools_framework.py',
    'caelum_payload_generator.py': 'src/caelum/payload_generator.py',
    'caelum_api_simplified.py': 'src/caelum/api_simplified.py',
    'caelum_mcp.py': 'src/caelum/mcp_server.py',
    'caelum-mcp.json': 'config/mcp_config.json',
    'Dockerfile': 'deploy/Dockerfile'
}

for src, dst in moves.items():
    if os.path.exists(src):
        shutil.move(src, dst)

# Move static files
if os.path.exists('static'):
    for f in os.listdir('static'):
        shutil.move(os.path.join('static', f), os.path.join('src/caelum/static', f))
    try: os.rmdir('static')
    except: pass

# Move fix scripts
for f in os.listdir('.'):
    if f.startswith('fix_') or f.startswith('fixer_') and f.endswith('.py'):
        shutil.move(f, os.path.join('scripts/hotfixes', f))

# Create __init__.py
with open('src/caelum/__init__.py', 'w', encoding='utf-8') as f:
    f.write("# CAELUM Package\n")

# 3. Update imports in .py files
replacements = {
    r'caelum_tools_framework': r'tools_framework',
    r'caelum_ai_analyzer': r'ai_analyzer',
    r'caelum_session_manager': r'session_manager',
    r'caelum_payload_generator': r'payload_generator',
    r'caelum_api_simplified': r'api_simplified',
    r'caelum_mcp': r'mcp_server',
}

ai_comments = [
    re.compile(r'#\s*Generated by AI.*?\n', re.IGNORECASE),
    re.compile(r'#\s*Created by AI.*?\n', re.IGNORECASE),
    re.compile(r'#\s*AI辅助生成.*?\n', re.IGNORECASE),
    re.compile(r'#\s*Here is the code.*?\n', re.IGNORECASE),
    re.compile(r'#\s*以下是实现代码.*?\n', re.IGNORECASE),
]

for root, dirs, files in os.walk('src/caelum'):
    for file in files:
        if file.endswith('.py'):
            filepath = os.path.join(root, file)
            with open(filepath, 'r', encoding='utf-8') as f:
                content = f.read()
            
            # Replace imports
            for old, new in replacements.items():
                content = re.sub(rf'\b{old}\b', new, content)
            
            # Cleanup AI comments
            for regex in ai_comments:
                content = regex.sub('', content)

            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(content)

# 4. Update Dockerfile running path
if os.path.exists('deploy/Dockerfile'):
    with open('deploy/Dockerfile', 'r', encoding='utf-8') as f:
        d_content = f.read()
    d_content = d_content.replace('caelum_server.py', 'src/caelum/server.py')
    with open('deploy/Dockerfile', 'w', encoding='utf-8') as f:
        f.write(d_content)

print("Restructuring Complete.")